Revert "fix: broken SQL statement"
This reverts commit 49db5256343046173373ab24c311597077ac8fb9.

reverting because it broke the tests (they were failing with the error

     PDOException: SQLSTATE[HY000]: General error: 1 near "IGNORE": syntax error

)